#!/usr/bin/env bash
# Installs or checks the WSL deployment adapter for the ScratchEditor
# external prompt editor. Run from inside WSL; the Windows stable editor is
# called through a small wrapper that converts WSL paths with wslpath.

set -euo pipefail

projectRoot="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
action="${1:-install}"

case "$action" in
    install|check) ;;
    *)
        echo "usage: $0 install|check" >&2
        exit 2
        ;;
esac

if [ -z "${WSL_DISTRO_NAME:-}" ]; then
    echo "This script must be run inside WSL." >&2
    exit 1
fi

if ! command -v wslpath >/dev/null 2>&1; then
    echo "wslpath is required but is not available." >&2
    exit 1
fi

hostLocalAppData=""
if [ -n "${LOCALAPPDATA:-}" ]; then
    hostLocalAppData="$(wslpath -u "${LOCALAPPDATA}")"
fi
if [ -z "$hostLocalAppData" ]; then
    for candidate in /mnt/c/Users/*/AppData/Local; do
        if [ -f "$candidate/ScratchEditor/CodexEditor/ScratchEditor.exe" ]; then
            hostLocalAppData="$candidate"
            break
        fi
    done
fi

if [ -z "$hostLocalAppData" ]; then
    echo "Unable to find the host ScratchEditor stable installation under /mnt/c/Users/*/AppData/Local." >&2
    exit 1
fi

stableEditor="$hostLocalAppData/ScratchEditor/CodexEditor/ScratchEditor.exe"
wrapperDir="$HOME/.local/bin"
wrapper="$wrapperDir/scratcheditor-external-editor"
bashrc="$HOME/.bashrc"
startMarker="# >>> ScratchEditor Codex external editor (WSL) >>>"
endMarker="# <<< ScratchEditor Codex external editor (WSL) <<<"
managedBy="# Managed by ${projectRoot}/scripts/configure-codex-editor-wsl.sh"

if [ "$action" = "check" ]; then
    failed=0
    if [ ! -f "$stableEditor" ]; then
        echo "FAIL: stable editor not found: $stableEditor" >&2
        failed=1
    fi
    if [ ! -x "$wrapper" ]; then
        echo "FAIL: WSL wrapper is missing or not executable: $wrapper" >&2
        failed=1
    fi
    if [ ! -f "$bashrc" ]; then
        echo "FAIL: $bashrc does not exist" >&2
        failed=1
    else
        if ! grep -qF "$startMarker" "$bashrc" \
            || ! grep -qF "$endMarker" "$bashrc" \
            || ! grep -qF "export VISUAL='code --wait'" "$bashrc" \
            || ! grep -qF "export VISUAL='$wrapper'" "$bashrc" \
            || ! grep -qF 'export EDITOR="$VISUAL"' "$bashrc"; then
            echo "FAIL: $bashrc is not configured for the ScratchEditor WSL external editor" >&2
            failed=1
        fi
    fi
    if [ "$failed" -eq 0 ]; then
        echo "PASS: WSL external editor configuration is complete"
        exit 0
    fi
    exit 1
fi

if [ ! -f "$stableEditor" ]; then
    echo "Stable editor not found: $stableEditor" >&2
    echo "Build and install ScratchEditor on Windows first." >&2
    exit 1
fi

mkdir -p "$wrapperDir"

wrapperText="$(cat <<EOF
#!/usr/bin/env bash
# Generated by ScratchEditor scripts/configure-codex-editor-wsl.sh.
# WSL deployment adapter for the ScratchEditor external prompt editor.
set -u

STABLE_EDITOR="$stableEditor"

if [ "\$#" -ne 1 ]; then
    echo "usage: scratcheditor-external-editor <file>" >&2
    exit 2
fi

file="\$1"

if [ ! -f "\$file" ]; then
    echo "ScratchEditor WSL wrapper: file not found: \$file" >&2
    exit 1
fi

if [ ! -f "\$STABLE_EDITOR" ]; then
    echo "ScratchEditor WSL wrapper: stable editor not found: \$STABLE_EDITOR" >&2
    exit 1
fi

if ! command -v wslpath >/dev/null 2>&1; then
    echo "ScratchEditor WSL wrapper: wslpath is not available" >&2
    exit 1
fi

win_file="\$(wslpath -w "\$file")"

"\$STABLE_EDITOR" --wait "\$win_file"
status=\$?
exit "\$status"
EOF
)"

wrapperTemp="$(mktemp)"
trap 'rm -f "$wrapperTemp"' EXIT
printf '%s\n' "$wrapperText" > "$wrapperTemp"
chmod +x "$wrapperTemp"
mv "$wrapperTemp" "$wrapper"
trap - EXIT

managedBlock="$(cat <<EOF
$startMarker
$managedBy
if [ "\${TERM_PROGRAM:-}" = "vscode" ]; then
    export VISUAL='code --wait'
else
    export VISUAL='$wrapper'
fi
export EDITOR="\$VISUAL"
$endMarker
EOF
)"

if [ -f "$bashrc" ] && [ ! -f "$bashrc.scratcheditor-wsl.bak" ]; then
    cp "$bashrc" "$bashrc.scratcheditor-wsl.bak"
fi

bashrcTemp="$(mktemp)"
trap 'rm -f "$bashrcTemp"' EXIT
if [ -f "$bashrc" ]; then
    awk -v start="$startMarker" -v end="$endMarker" -v block="$managedBlock" '
        $0 == start { skip = 1; next }
        $0 == end { skip = 0; next }
        !skip { print }
        END { print block }
    ' "$bashrc" > "$bashrcTemp"
else
    : > "$bashrcTemp"
    printf '%s\n' "$managedBlock" >> "$bashrcTemp"
fi
mv "$bashrcTemp" "$bashrc"
trap - EXIT

echo "WSL external editor configuration installed."
echo "Stable editor: $stableEditor"
echo "Wrapper: $wrapper"
echo "Open a new WSL terminal (or restart Codex) before using Ctrl+G."
